### ISSUE TITLE
interact: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by adamflott** [yogsototh/holy-project#6]
On OSX Yosemite with GHC 7.10.2
    
    $ ghc-pkg list|grep holy
        holy-project-0.2.0.0
    $ holy-project
    Bridgekeeper: Stop!
    Bridgekeeper: Who would cross the Bridge of Death
    Bridgekeeper: must answer me these questions three,
    Bridgekeeper: ere the other side he see.
    Sir Yourself: Ask me the questions, bridgekeeper, I am not afraid.
    
    Bridgekeeper: What is your project name?
    > whatever
    
    Bridgekeeper: What is your name? (Adam Flott)
    >
    
    Bridgekeeper: What is your email? (adam@adamflott.com)
    >
    
    Bridgekeeper: What is your github account? ("adamflott")
    >
    
    Bridgekeeper: What is your project in less than a dozen word??
    > blah blah blah
    
            .gitignore
            auto-update
            LICENSE
            Setup.hs
            interact
    holy-project: /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0/scaffold/interact: openFile: does not exist (No such file or directory)

And the files in the scaffold dir:

    $ find /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0/
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0/
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/auto-update
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/gitignore
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/LICENSE
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/project.cabal
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/Setup.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src/Main.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src/ModuleName
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src/ModuleName/Coconut.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src/ModuleName/Swallow.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/src/ModuleName.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/ModuleName
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/ModuleName/Coconut
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/ModuleName/Coconut/Test.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/ModuleName/Swallow
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/ModuleName/Swallow/Test.hs
    /Users/aflott/.cabal/share/x86_64-osx-ghc-7.10.2/holy-project-0.2.0.0//scaffold/test/Test.hs

**Comment by yogsototh** [comment]
Should be fixed with 0.2.0.1
